networks:
  backend:

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - ~/Documents/inception/srcs/requirements/nginx/log:/var/log/nginx
      - ~/Documents/inception/srcs/requirements/wordpress/website:/var/www/html
    networks:
      - backend
    ports:
      - '443:443'
    expose:
      - '443'
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    volumes:
      - ~/Documents/inception/srcs/requirements/wordpress/website:/var/www/html
    networks:
      - backend
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USR: ${WP_ADMIN_USR}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USR: ${WP_USR}
      WP_PWD: ${WP_PWD}
      WP_EMAIL: ${WP_EMAIL}
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - ~/Documents/inception/srcs/requirements/mariadb/data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}
    restart: always
